### ISSUE TITLE
Test Flight with a single Copter

### ISSUE THREAD

**Issue by steup** [maxct/paparazzi#3]
Fly with multiple Copters to analyse differences

**Comment by maxct** [comment]
my suggested scenarios:

starting position:
- 1,5m distance to the walls (window direction)
- 1m distance to the other walls

scenarios:
- 1a autonomous starting and stationary hovering Finken301
- 1b autonomous starting and stationary hovering Finken302
- 2a autonomous flying Finken301
- 2b autonomous flying Finken302
- 3a autonomous flying with user input (flying a defined path) Finken301
- 3b autonomous flying with user input (flying a defined path) Finken302

**Comment by tishur** [comment]
My offers, based on my and Andrew conversation:
1. Finish scenarious, suggested by Max for both copters with this clarifications:
a). Join scenarios 1 and 2 in one and then divide them after analysis.

**Comment by tishur** [comment]
My offers, based on experience from latest experiments and my conversation with Andrew:
1. Finish scenarious, suggested by Max for both copters with this clarifications:
a). Join scenarios 1 and 2 in one and then divide them after analysis. Flying time: one minute. Goal: check stabilization time and autonomous behavior. Important parameters: height, time for stabilization, distance from walls, propellers behavior, etc.
b). In third scenario continue to check changes copter behavior after simple commands provided by remote control. Goal: fly one meter from start line and then stabilize. Flying time: 20 seconds for stabilization.  Important parameters: height, propellers behavior in every step of experiment, time fo stabilization after reaching the goal point, etc.
c). At least 3 experiments in every scenario.
2. Create one wiki page for every experiment with some observations and simple data processing. My suggestion: one responsible person for every experiment. This item actually refers to the next issue "Evaluate Data of Test Flight".

**Comment by maxct** [comment]
We've done some testflights with Finken 302 could get data for the evaluation. It was not possible to get satifying data with the Finken 301 because it always crashed right after the launch.

**Comment by maxct** [comment]
some images from a testflight
![15_12_01__18_04_10all](https://cloud.githubusercontent.com/assets/15417995/11517442/c43cb946-9889-11e5-949d-7d7970832e29.png)
![15_12_01__18_04_10fb](https://cloud.githubusercontent.com/assets/15417995/11517443/c44eb416-9889-11e5-93ba-d918c331c18b.png)
![15_12_01__18_04_10lr](https://cloud.githubusercontent.com/assets/15417995/11517444/c45664ea-9889-11e5-9cdf-b549ea6c23ed.png)

**Comment by maxct** [comment]
![15_12_01__17_42_01](https://cloud.githubusercontent.com/assets/15417995/11528869/b67caff4-98e9-11e5-911d-4d4de3ff5a21.png)

**Comment by maxct** [comment]
![plotideal1](https://cloud.githubusercontent.com/assets/15417995/11607963/6c73ded0-9b5c-11e5-8911-274affbcf9df.png)
![plotideal2](https://cloud.githubusercontent.com/assets/15417995/11607964/6c762136-9b5c-11e5-91cb-c46f10f56bca.png)
![plotreal2](https://cloud.githubusercontent.com/assets/15417995/11607961/6c6c6cd6-9b5c-11e5-97f3-af9287d20362.png)
![plotreal1](https://cloud.githubusercontent.com/assets/15417995/11607962/6c6c87f2-9b5c-11e5-970a-5b6fabf8d119.png)

**Comment by maxct** [comment]
![plotideal1](https://cloud.githubusercontent.com/assets/15417995/11612970/8313a030-9c10-11e5-86ba-882f601280ec.png)
![plotideal2](https://cloud.githubusercontent.com/assets/15417995/11612971/8326e406-9c10-11e5-9c84-af66835ff20f.png)
![plotreal1](https://cloud.githubusercontent.com/assets/15417995/11612974/88c65ed2-9c10-11e5-8ef9-236eda2d99d1.png)
![plotreal2](https://cloud.githubusercontent.com/assets/15417995/11612975/88c8e30a-9c10-11e5-8f3c-bf863e674a52.png)

**Comment by maxct** [comment]
![plotreal1](https://cloud.githubusercontent.com/assets/15417995/11685432/2ac36896-9e79-11e5-900d-28497e0fb0d4.png)
![plotreal2](https://cloud.githubusercontent.com/assets/15417995/11685433/2c18a63e-9e79-11e5-9b74-677ab18a2d17.png)
