### ISSUE TITLE
Evaluate Data of Test Flight

### ISSUE THREAD

**Issue by steup** [maxct/paparazzi#4]
- Evaluate single Copters
- Evaluate difference between copters

**Comment by tishur** [comment]
We've decided to write wikipages to describe experiments and evaluating of receiving data. It will be one wikipage for results of every scenario.
- 1-2 scenarios(we are not sure divide them or not) is assigned to Alexei.
- 3-rd scenario is assigned to Andrew.
- 4-th scenario is assigned to Max.

**Comment by maxct** [comment]
some comments from the meeting:
- for 1 scenario we should measure the noise of acc and pos(height) --> does ist change with an other copter in the same state / flying
-  same for scenario 2
  --> scenario: one copter in a "sweat spot" (in a corner) and one other copter is manually flying next to it. 
- for scenario 4b we should analyse the noise with high- and lowpassfiltering
- for scenario 4a we should try to use a quadratic arena (3x3)

**Comment by tishur** [comment]
Done. But can be reopen, if in will be necessary during next milestone.
