### ISSUE TITLE
Test Flights

### ISSUE THREAD

**Issue by steup** [maxct/paparazzi#7]
- Define Scenario
- Fly and log data

**Comment by maxct** [comment]
Notes from the meeting today:
- Starting
- Flying without input (with wall avoidance)
- Flying a defined path

All Flights should take part on the same height!

**Comment by maxct** [comment]
Scenarios referring the 4th single copter scenario:
- idealized
  - Same as single copter scenario with an additional copter (same height, 1m distance at 180 degrees). The sonar sensor of the second copter should point towards the first copter
- realistic
  - 1 copter (rc_passthrough) should stay at center, second copter flys in wall_avoidance mode, 1 min
  - 1 copter (rc_passthrough) should stay at center, second copter (rc_passthrough) surrounds the first copter, 1 min

**Comment by tishur** [comment]
Scenario update of the 1-2th single copter scenario:
- first 10 seconds copters are on the ground
- autonomous flight of two copters: 
  - both copters in rc_passthrough.
  - one in wall_avoidance mode, second in rc_passthrough. Pilot of second tries avoid first copter. 2 minutes of flight. Then change copters and do the same.
  - both copters in wall_avoidance mode. 2 minutes of flight.
  - maybe, it would be necessary to change some parameters of wall_avoidance.

Some ideas: 
- find stable spots.
- find secure distance between copters.

**Comment by AndrewML** [comment]
Multi-Copter flight scenarios based on 3d one from single copter case:
- one copter is flying at one spot, another is 2 meters from it and moves towards 1 meter
- one copter is flying at one spot, another moves 1-2 meters orthogonally to first direction
- _one copter is flying at the center of arena, another moves around it from one side to another_

for all situations play with wall-avoid and rc_passthrough modes (the best case is to check all combinations).

**Comment by AndrewML** [comment]
Most of experiments were done and data were collected.
